#!/bin/sh
#
# Start olad
#

OLA_ARGS=--daemon

start() {
        printf "Starting olad: "
	/usr/sbin/ifconfig eth0 192.168.1.3 netmask 255.255.255.0 up && /bin/olad $OLA_ARGS
        echo "OK"
}

stop() {
        printf "Stopping logging: "
	/bin/killall olad
        echo "OK"
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

